name: 'Supabase Storage Upload'
description: 'Uploads files to a Supabase storage bucket'
author: 'brendenehlers'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  repo_directory:
    description: 'Root directory within the actions worker'
    required: true
    default: '${{ github.workspace }}'
  upload_directory_path:
    description: 'The directory within your project to upload the files from'
    required: true

# Define your outputs here.
outputs:
  message:
    description: 'TEMP'

runs:
  using: node20
  main: dist/index.js
