name: 'Supabase Storage Upload'
description: 'Uploads files to a Supabase storage bucket'
author: 'brendenehlers'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'hard-drive'
  color: 'green'

# Define your inputs here.
inputs:
  repo_directory:
    description: 'Root directory within the actions worker'
    required: true
    default: '${{ github.workspace }}'
  upload_directory_path:
    description: 'The directory within your project to upload the files from'
    required: true
  bucket_name:
    description: 'The Supabase bucket to upload the files to'
    required: true

# Define your outputs here.
outputs:
  message:
    description:
      'Output of the action, "Files uploaded successfully" if all files were
      uploaded successfully'

runs:
  using: node20
  main: dist/index.js
